/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.playside.servicemessage

class Library {
  fun someLibraryMethod(): Boolean {
    return true
  }
}

fun String.printServiceMessage(vararg arguments: Pair<String, Any?>) {
  val content =
      arguments
          .filter { it.second != null }
          .joinToString(separator = " ") { "${it.first}='${it.second}'" }
  println("##teamcity[${this} $content]")
}
