/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.playside.servicemessage

import kotlin.test.Test
import kotlin.test.assertTrue

class InspectionTest {
    @Test fun inspectionClassPrintsValid() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
